/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Essentials.Medicine;
import java.awt.CardLayout;
import java.awt.Component;
import static java.lang.Boolean.TRUE;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manaa
 */
public class ManageMedicineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMedicineJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private Medicine medicine;
    private PharmacyEnterprise enterprise;
    private String medName = "";
    private String cond;
    public ManageMedicineJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem business ) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.medicine = null;
        this.enterprise = (PharmacyEnterprise)enterprise;
        populateMedTable();
        initializeFields();
    }
    public ManageMedicineJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem business,String name,String cond) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.medicine = null;
        this.enterprise = (PharmacyEnterprise)enterprise;
        this.medName = name;
        this.cond = cond;
        populateMedTable();
        initializeFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateMedTable(){
        DefaultTableModel model = (DefaultTableModel)medTable.getModel();
        model.setRowCount(0);

         for(Medicine med: enterprise.getMedicineCatalog().getMedicineList()){
            Object row[] = new Object[5];
                 row[0] = med;
                 row[1] = med.getDosage();
                 row[2] = med.getPrice();
                 row[3] = med.getQuantity();
                 row[4] = med.getDemand();
                 model.addRow(row);                 
        }
    }
    public void initializeFields(){
        btnCreate.setEnabled(false);
        btnSave.setEnabled(false);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        medTable = new javax.swing.JTable();
        medPanel = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDose = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtQuant = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnEnt = new javax.swing.JRadioButton();
        btnResp = new javax.swing.JRadioButton();
        btnHeart = new javax.swing.JRadioButton();
        btnFever = new javax.swing.JRadioButton();
        btnDiab = new javax.swing.JRadioButton();
        btnPain = new javax.swing.JRadioButton();
        btnCovid = new javax.swing.JRadioButton();
        btnOther = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        btnUpdate.setText("Update Medicine");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Add NEW Medicine");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        medTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Medicine Name", "Dosage", "Price", "Quantity", "Demand"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medTable);

        medPanel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Name");

        jLabel2.setText("Dosage(mg)");

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jLabel3.setText("Price");

        jLabel4.setText("Quantity");

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel6.setText("Condition");

        btnEnt.setText("ENT");
        btnEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntActionPerformed(evt);
            }
        });

        btnResp.setText("Respiratory problems");
        btnResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespActionPerformed(evt);
            }
        });

        btnHeart.setText("Heart-Related");
        btnHeart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeartActionPerformed(evt);
            }
        });

        btnFever.setText("Fever");
        btnFever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeverActionPerformed(evt);
            }
        });

        btnDiab.setText("Diabetes-Related");
        btnDiab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiabActionPerformed(evt);
            }
        });

        btnPain.setText("Painkiller");
        btnPain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPainActionPerformed(evt);
            }
        });

        btnCovid.setText("Covid-Relief");
        btnCovid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCovidActionPerformed(evt);
            }
        });

        btnOther.setText("Other");
        btnOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout medPanelLayout = new javax.swing.GroupLayout(medPanel);
        medPanel.setLayout(medPanelLayout);
        medPanelLayout.setHorizontalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(medPanelLayout.createSequentialGroup()
                        .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(medPanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1)
                                .addGap(124, 124, 124)
                                .addComponent(jLabel2)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel3))
                            .addGroup(medPanelLayout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDose, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(medPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(medPanelLayout.createSequentialGroup()
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medPanelLayout.createSequentialGroup()
                                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(medPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnEnt)
                                        .addGap(14, 14, 14)
                                        .addComponent(btnResp)
                                        .addGap(20, 20, 20))
                                    .addGroup(medPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCovid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(medPanelLayout.createSequentialGroup()
                                        .addComponent(btnDiab)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPain))
                                    .addGroup(medPanelLayout.createSequentialGroup()
                                        .addComponent(btnHeart)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFever)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnOther)))
                                .addGap(424, 424, 424))))))
        );
        medPanelLayout.setVerticalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medPanelLayout.createSequentialGroup()
                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(medPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnDiab)
                    .addComponent(btnPain)
                    .addComponent(btnCovid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnt)
                    .addComponent(btnResp)
                    .addComponent(btnHeart)
                    .addComponent(btnFever)
                    .addComponent(btnOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel5.setText("Manage Supplies");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jLabel5)
                .addGap(298, 298, 298))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(medPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(medPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = medTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a Medicine row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        medicine= (Medicine)medTable.getValueAt(selectedRow, 0);
        txtName.setText(medicine.getName());
        txtPrice.setText(String.valueOf(medicine.getPrice()));
        txtDose.setText(String.valueOf(medicine.getDosage()));
        txtQuant.setText(String.valueOf(medicine.getQuantity()));
        switch(medicine.getCondition()){
            case "Covid":
                btnCovid.setSelected(true);
                cond = "Covid";
            case "Other":
                btnOther.setSelected(true);
                cond="Other";
            case "Ent":
                btnEnt.setSelected(true);
                cond="Ent";
            case "Diabetes":
                btnDiab.setSelected(true);
                cond="Diabetes";
            case "Resp":
                btnResp.setSelected(true);
                cond="Resp";
            case "Pain":
                btnPain.setSelected(true);
                cond="Pain";
            case "Heart":
                btnHeart.setSelected(true);
                cond="Heart";
                
        }
        medPanel.setEnabled(true);
        btnCreate.setEnabled(false);
        btnSave.setEnabled(true);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        medPanel.setEnabled(true);
        btnCreate.setEnabled(true);
        btnSave.setEnabled(false);
        if(!medName.equals("")){
            txtName.setText(medName);
             switch(cond){
            case "Covid":
                btnCovid.setSelected(true);
                cond = "Covid";
            case "Other":
                btnOther.setSelected(true);
                cond="Other";
            case "Ent":
                btnEnt.setSelected(true);
                cond="Ent";
            case "Diabetes":
                btnDiab.setSelected(true);
                cond="Diabetes";
            case "Resp":
                btnResp.setSelected(true);
                cond="Resp";
            case "Pain":
                btnPain.setSelected(true);
                cond="Pain";
            case "Heart":
                btnHeart.setSelected(true);
                cond="Heart";
                
        }
                btnCovid.setEnabled(false);
                btnOther.setEnabled(false);
                btnEnt.setEnabled(false);
                btnDiab.setEnabled(false);
                btnResp.setEnabled(false);
                btnPain.setEnabled(false);
                 btnHeart.setEnabled(false);
            txtName.setEnabled(false);
           
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = medTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a Medicine row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Medicine m = (Medicine)medTable.getValueAt(selectedRow, 0);
        enterprise.getMedicineCatalog().removeMedicine(m);
        populateMedTable();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PharmacyAdminWorkAreaJPanel sysAdminwjp = (PharmacyAdminWorkAreaJPanel) component;
        sysAdminwjp.populateNewMedTable();
        sysAdminwjp.populatePatientRequests();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if((txtName.getText().equals("")) || (txtPrice.getText().equals("")) ||(txtQuant.getText().equals(""))||(txtDose.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Name, Dose, Quantity and Price are mandatory!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String priceRegex ="[0-9]+\\.[0-9]{2,}";
        Pattern namePattern = Pattern.compile(priceRegex);
        Matcher checkFirstName = namePattern.matcher(txtPrice.getText());
        boolean checkNameMatch = checkFirstName.matches();
        if(!(checkNameMatch == TRUE)){
            JOptionPane.showMessageDialog(null, "Please enter Price in decimal format only!!\n(mininmum 2 digits after decimal)", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int dose = 0;
        int quant = 0;
        try{
            dose = Integer.parseInt(txtDose.getText());
            quant = Integer.parseInt(txtQuant.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter dosage and quantity in integer format only", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if((dose <= 0) ||(quant <= 0)){
            JOptionPane.showMessageDialog(null, "Dosage and quantity need tp be more than zero!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        medicine.setName(txtName.getText());
        medicine.setDosage(dose);
        medicine.setPrice(Double.parseDouble(txtPrice.getText()));
        medicine.setQuantity(quant);
        medicine.setCondition(cond);
        medicine.setUpdateDate();
        int dem = (medicine.getDemand() - medicine.getQuantity());
        if(dem <= 0){
            medicine.setDemand(0);
        }else{
            medicine.setDemand(dem);
        }
        enterprise.getMedicineCatalog().updateMedicine(medicine);
        populateMedTable();
        JOptionPane.showMessageDialog(null, "Medicine Updated successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if((txtName.getText().equals("")) || (txtPrice.getText().equals("")) ||(txtQuant.getText().equals(""))||(txtDose.getText().equals("")) || cond.equals("")){
            JOptionPane.showMessageDialog(null, "Name, Dose, Quantity,Condition and Price are mandatory!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String priceRegex ="[0-9]+\\.[0-9]{2,}";
        Pattern namePattern = Pattern.compile(priceRegex);
        Matcher checkFirstName = namePattern.matcher(txtPrice.getText());
        boolean checkNameMatch = checkFirstName.matches();
        if(!(checkNameMatch == TRUE)){
            JOptionPane.showMessageDialog(null, "Please enter Price in decimal format only!!\n(mininmum 2 digits after decimal)", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int dose = 0;
        int quant = 0;
        try{
            dose = Integer.parseInt(txtDose.getText());
            quant = Integer.parseInt(txtQuant.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter dosage and quantity in integer format only", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if((dose <= 0) ||(quant <= 0)){
            JOptionPane.showMessageDialog(null, "Dosage and quantity need tp be more than zero!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Medicine med = new Medicine(txtName.getText(),Double.parseDouble(txtPrice.getText()),quant,dose);
        med.setCondition(cond);
        med.setUpdateDate();
        med.setDemand(0);

        enterprise.getMedicineCatalog().addMedicine(med);
        populateMedTable();
        JOptionPane.showMessageDialog(null, "Medicine Created successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntActionPerformed
        // TODO add your handling code here:
                btnPain.setSelected(false);
        btnResp.setSelected(false);
        btnHeart.setSelected(false);
        btnDiab.setSelected(false);
        btnOther.setSelected(false);
        btnFever.setSelected(false);
        btnCovid.setSelected(false);
        cond = "Ent";
    }//GEN-LAST:event_btnEntActionPerformed

    private void btnFeverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeverActionPerformed
        // TODO add your handling code here:
                btnPain.setSelected(false);
        btnResp.setSelected(false);
        btnHeart.setSelected(false);
        btnDiab.setSelected(false);
        btnCovid.setSelected(false);
        btnOther.setSelected(false);
        btnEnt.setSelected(false);
        cond = "Fever";
    }//GEN-LAST:event_btnFeverActionPerformed

    private void btnDiabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiabActionPerformed
        // TODO add your handling code here:
                btnPain.setSelected(false);
        btnResp.setSelected(false);
        btnHeart.setSelected(false);
        btnCovid.setSelected(false);
        btnFever.setSelected(false);
        btnOther.setSelected(false);
        btnEnt.setSelected(false);
        cond = "Diabetes";
    }//GEN-LAST:event_btnDiabActionPerformed

    private void btnPainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPainActionPerformed
        // TODO add your handling code here:
                btnCovid.setSelected(false);
        btnResp.setSelected(false);
        btnHeart.setSelected(false);
        btnDiab.setSelected(false);
        btnFever.setSelected(false);
        btnEnt.setSelected(false);
        btnOther.setSelected(false);
        cond = "Pain";
    }//GEN-LAST:event_btnPainActionPerformed

    private void btnCovidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCovidActionPerformed
        // TODO add your handling code here:
        btnPain.setSelected(false);
        btnResp.setSelected(false);
        btnHeart.setSelected(false);
        btnDiab.setSelected(false);
        btnFever.setSelected(false);
        btnEnt.setSelected(false);
        btnOther.setSelected(false);
        cond = "Covid";
        
    }//GEN-LAST:event_btnCovidActionPerformed

    private void btnHeartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeartActionPerformed
        // TODO add your handling code here:
                btnPain.setSelected(false);
        btnResp.setSelected(false);
        btnCovid.setSelected(false);
        btnDiab.setSelected(false);
        btnFever.setSelected(false);
        btnEnt.setSelected(false);
        btnOther.setSelected(false);
        cond = "Heart";
    }//GEN-LAST:event_btnHeartActionPerformed

    private void btnRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespActionPerformed
        // TODO add your handling code here:
                btnPain.setSelected(false);
        btnCovid.setSelected(false);
        btnHeart.setSelected(false);
        btnDiab.setSelected(false);
        btnFever.setSelected(false);
        btnEnt.setSelected(false);
        btnOther.setSelected(false);
        cond = "Resp";
    }//GEN-LAST:event_btnRespActionPerformed

    private void btnOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtherActionPerformed
        // TODO add your handling code here:
                        btnPain.setSelected(false);
        btnCovid.setSelected(false);
        btnHeart.setSelected(false);
        btnDiab.setSelected(false);
        btnFever.setSelected(false);
        btnEnt.setSelected(false);
        btnResp.setSelected(false);
        cond = "other";
    }//GEN-LAST:event_btnOtherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnCovid;
    private javax.swing.JButton btnCreate;
    private javax.swing.JRadioButton btnDiab;
    private javax.swing.JRadioButton btnEnt;
    private javax.swing.JRadioButton btnFever;
    private javax.swing.JRadioButton btnHeart;
    private javax.swing.JRadioButton btnOther;
    private javax.swing.JRadioButton btnPain;
    private javax.swing.JButton btnRemove;
    private javax.swing.JRadioButton btnResp;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel medPanel;
    private javax.swing.JTable medTable;
    private javax.swing.JTextField txtDose;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuant;
    // End of variables declaration//GEN-END:variables
}
