/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.InsurancePolicy.InsurancePolicy;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.MenuComponent;
import static java.lang.Boolean.TRUE;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Anjali
 */
public class CreatePolicyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePolicyWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecosystem;
    InsurancePolicy i;
    UserAccount account;
    String enterPriceName;
    
    public CreatePolicyWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem ecosystem,UserAccount account) {
    initComponents();
    this.ecosystem=ecosystem;
    this.enterprise=enterprise;
    this.userProcessContainer=userProcessContainer;
    this.account=account;
    enterPriceName=enterprise.getName();
    
    for(Network network:ecosystem.getNetworkList()){
    for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
    if(e.getEnterpriseType().getValue().equals("Hospital")){
           jComboHospital.addItem(e.getName());   
    }
    else if(e.getEnterpriseType().getValue().equals("Pharmacy"))
            {jComboPharmacy.addItem(e.getName());   
    }
    else if(e.getEnterpriseType().getValue().equals("Laboratory"))
            {jComboLaboratories.addItem(e.getName());   
        
    }
    }
    }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTele3 = new javax.swing.JRadioButton();
        btnVision4 = new javax.swing.JRadioButton();
        btnHearing7 = new javax.swing.JRadioButton();
        btnFitness2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkBoxFamily = new javax.swing.JCheckBox();
        btnLab6 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPhar5 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMonthly = new javax.swing.JTextField();
        txtSpecialistCare = new javax.swing.JTextField();
        txtPrimaryCare = new javax.swing.JTextField();
        txtSurgery = new javax.swing.JTextField();
        txtLabServices = new javax.swing.JTextField();
        txtEmergencyRoomCare = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPolicyMax = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboHospital = new javax.swing.JComboBox<>();
        btnAddHospital = new javax.swing.JButton();
        jComboLaboratories = new javax.swing.JComboBox<>();
        btnAddLaboratory = new javax.swing.JButton();
        jComboPharmacy = new javax.swing.JComboBox<>();
        btnAddPharmacy = new javax.swing.JButton();
        btnDental = new javax.swing.JRadioButton();
        jLabel40 = new javax.swing.JLabel();
        txtInpatients = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListHospital = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtPolicyName1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtDeductible4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDeductible1 = new javax.swing.JTextField();
        checkBoxIndividual = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        jComboBoxAgeGroup = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Create Insurance Policy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 25, -1, -1));

        jLabel2.setText("Policy Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, -1));
        add(txtPolicyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 140, 117, -1));

        jLabel4.setText("Monthly Premium ($):");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Plan Features:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        btnTele3.setBackground(new java.awt.Color(204, 204, 204));
        btnTele3.setText("TeleHealth Services");
        add(btnTele3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        btnVision4.setBackground(new java.awt.Color(204, 204, 204));
        btnVision4.setText("Vision");
        add(btnVision4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        btnHearing7.setBackground(new java.awt.Color(204, 204, 204));
        btnHearing7.setText("Hearing");
        add(btnHearing7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, -1, -1));

        btnFitness2.setBackground(new java.awt.Color(204, 204, 204));
        btnFitness2.setText("Fitness Benifits");
        add(btnFitness2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel6.setText("Age Group :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel7.setText("Policy Type:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        checkBoxFamily.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxFamily.setText("Family");
        checkBoxFamily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkBoxFamilyMousePressed(evt);
            }
        });
        add(checkBoxFamily, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        btnLab6.setBackground(new java.awt.Color(204, 204, 204));
        btnLab6.setText("Laboratory Services");
        add(btnLab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Co-Payment After Deductable:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel9.setText("Primary Care ($):");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel10.setText("Specialist Care ($):");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        btnPhar5.setBackground(new java.awt.Color(204, 204, 204));
        btnPhar5.setText("Pharmacy");
        add(btnPhar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel12.setText("Emergency Room Care ($):");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jLabel13.setText("Laboratory Services ($):");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 170, -1));

        jLabel14.setText("Surgery ($):");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, -1, -1));
        add(txtMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 117, -1));
        add(txtSpecialistCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 50, -1));
        add(txtPrimaryCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 50, -1));
        add(txtSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 50, -1));
        add(txtLabServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 50, -1));
        add(txtEmergencyRoomCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 50, -1));

        jLabel15.setText("Policy Maximum($):");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));
        add(txtPolicyMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 117, -1));

        btnBack.setText("<-Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 28, -1, -1));

        btnCreate.setBackground(new java.awt.Color(204, 204, 204));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCreate.setText("Create Policy");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 492, 160, 40));

        jLabel11.setText("Hospitals:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jLabel16.setText("Laboratories:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        jLabel17.setText("Pharmacy:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, -1, -1));

        add(jComboHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 170, -1));

        btnAddHospital.setBackground(new java.awt.Color(204, 204, 204));
        btnAddHospital.setText("Add");
        btnAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalActionPerformed(evt);
            }
        });
        add(btnAddHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, -1, -1));

        add(jComboLaboratories, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 170, -1));

        btnAddLaboratory.setBackground(new java.awt.Color(204, 204, 204));
        btnAddLaboratory.setText("Add");
        btnAddLaboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLaboratoryActionPerformed(evt);
            }
        });
        add(btnAddLaboratory, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, -1, -1));

        add(jComboPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 690, 170, -1));

        btnAddPharmacy.setBackground(new java.awt.Color(204, 204, 204));
        btnAddPharmacy.setText("Add");
        btnAddPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPharmacyActionPerformed(evt);
            }
        });
        add(btnAddPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 690, -1, -1));

        btnDental.setBackground(new java.awt.Color(204, 204, 204));
        btnDental.setText("Dental");
        add(btnDental, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel40.setText("Inpatient Admissions ($):");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 190, -1));
        add(txtInpatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 50, -1));
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 552, -1, -1));

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("Laboratory:"));
        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 607, 178, 140));

        jList3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pharmacies"));
        jScrollPane3.setViewportView(jList3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 607, 178, 140));

        jListHospital.setBorder(javax.swing.BorderFactory.createTitledBorder("Hospitals :"));
        jListHospital.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jListHospital);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 178, 140));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Add hospitals,laboratories and pharmacies to the insurancy policy network:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel21.setText("ZipCode:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));
        add(txtPolicyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 110, -1));

        jLabel42.setText("Annual Out-of Pocket ($):");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));
        add(txtDeductible4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 117, -1));

        jLabel23.setText("Annual Deductible ($):");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        add(txtDeductible1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 117, -1));

        checkBoxIndividual.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxIndividual.setText("Individual");
        checkBoxIndividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkBoxIndividualMousePressed(evt);
            }
        });
        add(checkBoxIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 780, 180, -1));

        jComboBoxAgeGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18-30", "30-45", "45-60", "60-80", "80-100" }));
        add(jComboBoxAgeGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
     
        String e ="";
        
        if ((checkBoxFamily.isSelected()) || (checkBoxIndividual.isSelected())) {
        }else{ e = "Please choose a policy type";
        }

        

        if (!(checkNumber(txtSpecialistCare.getText())== TRUE)) {
            e = "Please enter only digits!";
            txtSpecialistCare.setBorder(new LineBorder(Color.RED, 2));   
        } 
        
        if (!(checkNumber(txtEmergencyRoomCare.getText()) == TRUE)) {
            e = "Please enter only digits!";
            txtEmergencyRoomCare.setBorder(new LineBorder(Color.RED, 2));   
        } 
        
        if (!(checkNumber(txtSurgery.getText()) == TRUE)) {
            e = "Please enter only digits!";
            txtSurgery.setBorder(new LineBorder(Color.RED, 2));    
        } 
        
        if (!(checkNumber(txtLabServices.getText()) == TRUE)) {
            e = "Please enter only digits!";
            txtLabServices.setBorder(new LineBorder(Color.RED, 2));    
        } 
        
        if (!(checkNumber(txtInpatients.getText()) == TRUE)) {
            e = "Please enter only digits!";
            txtInpatients.setBorder(new LineBorder(Color.RED, 2));   
        } 
        
        if (!(checkNumber(txtPrimaryCare.getText()) == TRUE)) {
            e = "Please enter only digits!";
            txtPrimaryCare.setBorder(new LineBorder(Color.RED, 2));
         }
        
        if (!(checkMoney(txtPolicyMax.getText()) == TRUE)) {
            e = "Please enter only , and digits !";
            txtPolicyMax.setBorder(new LineBorder(Color.RED, 2));
        } 

        if (!(checkMoney(txtDeductible1.getText()) == TRUE)) {
            e = "Please enter only , and digits !";
            txtDeductible1.setBorder(new LineBorder(Color.RED, 2)); 
        } 

        if (!(checkMoney(txtDeductible4.getText()) == TRUE)) {
            e = "Please enter only , and digits !";
            txtDeductible4.setBorder(new LineBorder(Color.RED, 2));
        }

        if (!(checkMoney(txtMonthly.getText()) == TRUE)) {
            e = "Please enter only , and digits !";
            txtMonthly.setBorder(new LineBorder(Color.RED, 2));
        } 
       
        if (txtPolicyMax.getText().equals("") || txtPolicyName.getText().equals("") || txtMonthly.getText().equals("") || txtDeductible1.getText().equals("") || txtPrimaryCare.getText().equals("") || txtDeductible4.getText().equals("")
                || txtSpecialistCare.getText().equals("") || txtEmergencyRoomCare.getText().equals("") || txtSurgery.getText().equals("") || txtLabServices.getText().equals("") || txtInpatients.getText().equals("") || txtPolicyName1.getText().equals("")) {
            e = "Please enter all the required field";           
        } 
        
      
      
        if(!(e.equals(""))){
            JOptionPane.showMessageDialog(null,e);
            return;
        }
        else{ 
            String dental;
            String fitness;
            String vision;
            String hearing;
            String laboratory;
            String pharmacy;
            String teleHealth;
            String policyType = null;
            
            String zipCode = txtPolicyName1.getText();
            String policyName = txtPolicyName.getText();
            double monthlyPremium = Double.parseDouble(txtMonthly.getText());
            double deductable =Double.parseDouble(txtDeductible1.getText());
            if (checkBoxFamily.isSelected()) {
                policyType = "Family";
            }
            if (checkBoxIndividual.isSelected()) {
                policyType = "Individual";
            }

            String policyMax = txtPolicyMax.getText();
            String OutOfPocket = txtDeductible4.getText();
            String ageGroup= (String) jComboBoxAgeGroup.getSelectedItem();

            if (btnDental.isSelected()) {
                dental = "Yes";
            } else {
                dental = "No";
            }

            if (btnVision4.isSelected()) {
                vision = "Yes";
            } else {
                vision = "No";
            }

            if (btnHearing7.isSelected()) {
                hearing = "Yes";
            } else {
                hearing = "No";
            }

            if (btnFitness2.isSelected()) {
                fitness = "Yes";
            } else {
                fitness = "No";
            }

            if (btnLab6.isSelected()) {
                laboratory = "Yes";
            } else {
                laboratory = "No";
            }

            if (btnPhar5.isSelected()) {
                pharmacy = "Yes";
            } else {
                pharmacy = "No";
            }

            if (btnTele3.isSelected()) {
                teleHealth = "Yes";
            } else {
                teleHealth = "No";
            }

            int primaryCare = Integer.parseInt(txtPrimaryCare.getText());
            int specialist = Integer.parseInt(txtSpecialistCare.getText());
            int emergency = Integer.parseInt(txtEmergencyRoomCare.getText());
            int surgery = Integer.parseInt(txtSurgery.getText());
            int laboratoryservices = Integer.parseInt(txtLabServices.getText());
            int inpatients = Integer.parseInt(txtInpatients.getText());

            i = ecosystem.getInsurancePolicyDirectory().addInsurancePolicy();
            i.setAgeGroup(ageGroup);
            i.setDental(dental);
            i.setEmergency(emergency);
            i.setFitness(fitness);
            i.setHearing(hearing);
            i.setInPatients(inpatients);
            i.setLaboratory(laboratory);
            i.setMonthlyPremium(monthlyPremium);
            i.setOutOfPocket(OutOfPocket);
            i.setPharmacy(pharmacy);
            i.setPolicyMax(policyMax);
            i.setPolicyName(policyName);
            i.setSurgery(surgery);
            i.setTeleHealth(teleHealth);
            i.setSpecialist(specialist);
            i.setPrimaryCare(primaryCare);
            i.setPolicyType(policyType);
            i.setLaboratoryservices(laboratoryservices);
            i.setVision(vision);
            i.setDeductable(deductable);
            i.setZipCode(zipCode);
            i.setUserName(account.getUsername());
            i.setEnterprise(enterPriceName);
            JOptionPane.showMessageDialog(null, "Successfully created!");

            
            
                                                        
        }

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalActionPerformed

        boolean t = ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList().isEmpty();
        if (t == false) {
            String x = (String) jComboHospital.getSelectedItem();

            i.addHospitals(x);

                DefaultListModel DLM = new DefaultListModel();
            
                for (int counter = 0; counter < i.getHospitalList().size(); counter++) {
                    DLM.addElement(i.getHospitalList().get(counter));
                }
            

            jListHospital.setModel(DLM);
            int y = jComboHospital.getSelectedIndex();
            jComboHospital.removeItemAt(y);
        } else {
            JOptionPane.showMessageDialog(null, "Please create the policy first!");

        }


      
    }//GEN-LAST:event_btnAddHospitalActionPerformed

    private void checkBoxFamilyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxFamilyMousePressed
        // TODO add your handling code here:
          if(checkBoxIndividual.isSelected()==true){
            
                    JOptionPane.showMessageDialog(null, "Only one checkbox can be selected!");
                    checkBoxFamily.setSelected(false);
        }
    }//GEN-LAST:event_checkBoxFamilyMousePressed

    private void checkBoxIndividualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxIndividualMousePressed
        // TODO add your handling code here:
         if(checkBoxFamily.isSelected()==true){
            
                    JOptionPane.showMessageDialog(null, "Only one checkbox can be selected!");
                    checkBoxIndividual.setSelected(false);
        }
    }//GEN-LAST:event_checkBoxIndividualMousePressed

    private void btnAddLaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLaboratoryActionPerformed
     boolean t =ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList().isEmpty();
      if (t==false)
      {  
       String x = (String) jComboLaboratories.getSelectedItem();
    
       i.addLaboratory(x);
       
      DefaultListModel DLL = new DefaultListModel();
      
      for(int counter=0;counter<i.getLaboratoryList().size();counter++)
      {DLL.addElement(i.getLaboratoryList().get(counter));
      }
      
      
      jList2.setModel(DLL);
      int y=jComboLaboratories.getSelectedIndex();
      jComboLaboratories.removeItemAt(y);
        }
      else{JOptionPane.showMessageDialog(null, "Please create the policy first!");
          
      }  
    }//GEN-LAST:event_btnAddLaboratoryActionPerformed

    private void btnAddPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPharmacyActionPerformed
        // TODO add your handling code here:
        boolean t =ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList().isEmpty();
      if (t==false)
      {
        String x = (String) jComboPharmacy.getSelectedItem();
    
       i.addPharmacy(x);
       
      DefaultListModel DLP = new DefaultListModel();
      
      {for(int counter=0;counter<i.getPharmacyList().size();counter++)
      {DLP.addElement(i.getPharmacyList().get(counter));
      }
      
      
      jList3.setModel(DLP);
      int y=jComboPharmacy.getSelectedIndex();
      jComboPharmacy.removeItemAt(y);
      }
      }
      else{JOptionPane.showMessageDialog(null, "Please create the policy first!");
          
      }
      
  
    }//GEN-LAST:event_btnAddPharmacyActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    String e="";
        if (i.getHospitalList().isEmpty()) {
            e = "Please add hospitals to the Policy";
        }
        if (i.getLaboratoryList().isEmpty()) {
            e = "Please add laboratory to the Policy";
        }
        if (i.getPharmacyList().isEmpty()) {
            e = "Please add pharmacy to the list";
        }
        
        if(!(e.equals(""))){
            JOptionPane.showMessageDialog(null, e);
        }else{txtPolicyMax.setText("");
            txtPolicyName.setText("");
            txtMonthly.setText("");
            txtDeductible1.setText("");
            txtPrimaryCare.setText("");
            txtDeductible4.setText("");
            txtSpecialistCare.setText("");
            txtEmergencyRoomCare.setText("");
            txtSurgery.setText("");
            txtLabServices.setText("");
            txtInpatients.setText("") ;
            txtPolicyName1.setText("");
 
            
            JOptionPane.showMessageDialog(null, "Successfully Submitted!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        InsuranceAdminWorkAreaJPanel iawa = (InsuranceAdminWorkAreaJPanel) component;
        iawa.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed
   public boolean checkNumber(String s){
      String nORegex = "^[0-9]*$";
        Pattern phonePattern = Pattern.compile(nORegex);       
        Matcher checkPhone = phonePattern.matcher(s);
        boolean number = checkPhone.matches();
        return number;
}
   
      public boolean checkMoney(String s){
        String nORegex = "^[0-9]+,*[0-9]*,*[0-9]*$";
        Pattern phonePattern = Pattern.compile(nORegex);       
        Matcher checkPhone = phonePattern.matcher(s);
        boolean number = checkPhone.matches();
        return number;
}
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHospital;
    private javax.swing.JButton btnAddLaboratory;
    private javax.swing.JButton btnAddPharmacy;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JRadioButton btnDental;
    private javax.swing.JRadioButton btnFitness2;
    private javax.swing.JRadioButton btnHearing7;
    private javax.swing.JRadioButton btnLab6;
    private javax.swing.JRadioButton btnPhar5;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JRadioButton btnTele3;
    private javax.swing.JRadioButton btnVision4;
    private javax.swing.JCheckBox checkBoxFamily;
    private javax.swing.JCheckBox checkBoxIndividual;
    private javax.swing.JComboBox<String> jComboBoxAgeGroup;
    private javax.swing.JComboBox<String> jComboHospital;
    private javax.swing.JComboBox<String> jComboLaboratories;
    private javax.swing.JComboBox<String> jComboPharmacy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jListHospital;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtDeductible1;
    private javax.swing.JTextField txtDeductible4;
    private javax.swing.JTextField txtEmergencyRoomCare;
    private javax.swing.JTextField txtInpatients;
    private javax.swing.JTextField txtLabServices;
    private javax.swing.JTextField txtMonthly;
    private javax.swing.JTextField txtPolicyMax;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyName1;
    private javax.swing.JTextField txtPrimaryCare;
    private javax.swing.JTextField txtSpecialistCare;
    private javax.swing.JTextField txtSurgery;
    // End of variables declaration//GEN-END:variables
}
