/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.InsurancePolicy.InsurancePolicy;
import Business.Network.Network;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anjali
 */
public class CreatePolicyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePolicyWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecosystem;
    InsurancePolicy i;
    
    public CreatePolicyWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem ecosystem) {
    initComponents();
    this.ecosystem=ecosystem;
    this.enterprise=enterprise;
    this.userProcessContainer=userProcessContainer;

    for(Network network:ecosystem.getNetworkList()){
    for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
    if(e.getEnterpriseType().getValue().equals("Hospital")){
           jComboHospital.addItem(e.getName());   
    }
    else if(e.getEnterpriseType().getValue().equals("Pharmacy"))
            { jComboLaboratories.addItem(e.getName());   
    }
    else if(e.getEnterpriseType().getValue().equals("Laboratory"))
            {jComboPharmacy.addItem(e.getName());   
        
    }
    }
    }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RButton3 = new javax.swing.JRadioButton();
        RButton4 = new javax.swing.JRadioButton();
        RButton7 = new javax.swing.JRadioButton();
        RButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkBoxFamily = new javax.swing.JCheckBox();
        RButton6 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RButton5 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMonthly = new javax.swing.JTextField();
        txtSpecialistCare = new javax.swing.JTextField();
        txtPrimaryCare = new javax.swing.JTextField();
        txtSurgery = new javax.swing.JTextField();
        txtLabServices = new javax.swing.JTextField();
        txtEmergencyRoomCare = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPolicyMax = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jComboHospital = new javax.swing.JComboBox<>();
        btnAddHospital = new javax.swing.JButton();
        jComboLaboratories = new javax.swing.JComboBox<>();
        btnAddLaboratory = new javax.swing.JButton();
        jComboPharmacy = new javax.swing.JComboBox<>();
        btnAddPharmacy = new javax.swing.JButton();
        RButton1 = new javax.swing.JRadioButton();
        jLabel40 = new javax.swing.JLabel();
        txtInpatients = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListHospital = new javax.swing.JList<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtPolicyName1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtDeductible4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDeductible1 = new javax.swing.JTextField();
        checkBoxIndividual = new javax.swing.JCheckBox();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Create Insurance Policy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 25, -1, -1));

        jLabel2.setText("Policy Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, -1));
        add(txtPolicyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 140, 117, -1));

        jLabel4.setText("Monthly Premium:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Plan Features:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        RButton3.setBackground(new java.awt.Color(204, 204, 204));
        RButton3.setText("TeleHealth Services");
        add(RButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        RButton4.setBackground(new java.awt.Color(204, 204, 204));
        RButton4.setText("Vision");
        add(RButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        RButton7.setBackground(new java.awt.Color(204, 204, 204));
        RButton7.setText("Hearing");
        add(RButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, -1, -1));

        RButton2.setBackground(new java.awt.Color(204, 204, 204));
        RButton2.setText("Fitness Benifits");
        add(RButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel6.setText("Age Group :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel7.setText("Policy Type:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, -1, -1));

        checkBoxFamily.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxFamily.setText("Family");
        checkBoxFamily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkBoxFamilyMousePressed(evt);
            }
        });
        add(checkBoxFamily, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 84, -1, -1));

        RButton6.setBackground(new java.awt.Color(204, 204, 204));
        RButton6.setText("Laboratory Services");
        add(RButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Co-Payment After Deductable:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel9.setText("Primary Care:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel10.setText("Specialist Care:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        RButton5.setBackground(new java.awt.Color(204, 204, 204));
        RButton5.setText("Pharmacy");
        add(RButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel12.setText("Emergency Room Care:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jLabel13.setText("Laboratory Services:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 170, -1));

        jLabel14.setText("Surgery:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, -1, -1));
        add(txtMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 117, -1));
        add(txtSpecialistCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 50, -1));
        add(txtPrimaryCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 50, -1));
        add(txtSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 50, -1));
        add(txtLabServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 50, -1));
        add(txtEmergencyRoomCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 50, -1));

        jLabel15.setText("Policy Maximum:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));
        add(txtPolicyMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 117, -1));

        btnBack.setText("<-Back");
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 28, -1, -1));

        btnCreate.setBackground(new java.awt.Color(204, 204, 204));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 492, 250, 50));

        jLabel11.setText("Hospitals:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jLabel16.setText("Laboratories:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        jLabel17.setText("Pharmacy:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(26, 26, 100, 1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(26, 26, 100, 1));
        add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 50, -1));

        add(jComboHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 170, -1));

        btnAddHospital.setBackground(new java.awt.Color(204, 204, 204));
        btnAddHospital.setText("Add");
        btnAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalActionPerformed(evt);
            }
        });
        add(btnAddHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, -1, -1));

        add(jComboLaboratories, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 170, -1));

        btnAddLaboratory.setBackground(new java.awt.Color(204, 204, 204));
        btnAddLaboratory.setText("Add");
        btnAddLaboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLaboratoryActionPerformed(evt);
            }
        });
        add(btnAddLaboratory, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, -1, -1));

        add(jComboPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 690, 170, -1));

        btnAddPharmacy.setBackground(new java.awt.Color(204, 204, 204));
        btnAddPharmacy.setText("Add");
        btnAddPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPharmacyActionPerformed(evt);
            }
        });
        add(btnAddPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 690, -1, -1));

        RButton1.setBackground(new java.awt.Color(204, 204, 204));
        RButton1.setText("Dental");
        add(RButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel40.setText("Inpatient Admissions:");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, -1));
        add(txtInpatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 50, -1));
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 552, -1, -1));

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("Laboratory:"));
        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 607, 178, 140));

        jList3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pharmacies"));
        jScrollPane3.setViewportView(jList3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 607, 178, 140));

        jListHospital.setBorder(javax.swing.BorderFactory.createTitledBorder("Hospitals :"));
        jListHospital.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jListHospital);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 178, 140));

        jLabel19.setText("Min:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel20.setText("Max:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Add hospitals,laboratories and pharmacies to the insurancy policy network:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel21.setText("ZipCode:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));
        add(txtPolicyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 110, -1));

        jLabel42.setText("Annual Out-of Pocket:");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));
        add(txtDeductible4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 117, -1));

        jLabel23.setText("Annual Deductible :");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        add(txtDeductible1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 117, -1));

        checkBoxIndividual.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxIndividual.setText("Individual");
        checkBoxIndividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkBoxIndividualMousePressed(evt);
            }
        });
        add(checkBoxIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String dental;
        String fitness;
        String vision;
        String hearing;
        String laboratory;
        String pharmacy;
        String teleHealth;
        String policyType = null;
        
        String policyName=txtPolicyName.getText();
        double monthlyPremium=Double.parseDouble(txtMonthly.getText());
        
        if(checkBoxFamily.isSelected())
        {
        policyType="Family";
        }
         if(checkBoxIndividual.isSelected())
        {
        policyType="Individual";
        }
        
       
        String policyMax=txtPolicyMax.getText();
        String OutOfPocket=txtDeductible4.getText();
        int ageMin=(Integer)jSpinner1.getValue();
        int ageMax =  (Integer)jSpinner2.getValue();
       
        if(RButton1.isSelected())
        {
        dental="Yes";
        }else {dental="No";
        }
        
        if(RButton2.isSelected())
        {
        vision="Yes";
        }else {vision="No";
        }
        
        if(RButton3.isSelected())
        {
        hearing="Yes";
        }else {hearing="No";
        }
        
        if(RButton4.isSelected())
        {
        fitness="Yes";
        }else {fitness="No";
        }
        
        if(RButton5.isSelected())
        {
        laboratory="Yes";
        }else {laboratory="No";
        }
        
        if(RButton6.isSelected())
        {
        pharmacy="Yes";
        }else {pharmacy="No";
        }
        
        if(RButton7.isSelected())
        {
        teleHealth="Yes";
        }else {teleHealth="No";
        }
        
        int primaryCare=Integer.parseInt(txtPrimaryCare.getText());
        int specialist=Integer.parseInt(txtSpecialistCare.getText());
        int emergency=Integer.parseInt(txtEmergencyRoomCare.getText());
        int surgery=Integer.parseInt(txtSurgery.getText());
        int laboratoryservices=Integer.parseInt(txtLabServices.getText());
        int inpatients=Integer.parseInt(txtInpatients.getText());
        
        i = ecosystem.getInsurancePolicyDirectory().addInsurancePolicy();
       
        i.setAgeMax(ageMax);
        i.setAgeMin(ageMin);
        i.setDental(dental);
        i.setEmergency(emergency);
        i.setFitness(fitness);
        i.setHearing(hearing);
        i.setInPatients(inpatients);
        i.setLaboratory(laboratory);
        i.setMonthlyPremium(monthlyPremium);
        i.setOutOfPocket(OutOfPocket);
        i.setPharmacy(pharmacy);
        i.setPolicyMax(policyMax);
        i.setPolicyName(policyName);
        i.setSurgery(surgery);
        i.setTeleHealth(teleHealth);
        i.setSpecialist(specialist);
        i.setPrimaryCare(primaryCare);
        i.setPolicyType(policyType);
        i.setLaboratoryservices(laboratoryservices);
        i.setVision(vision);
        
        
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalActionPerformed
      
      boolean t =ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList().isEmpty();
      if (t==false)
      {String x = (String) jComboHospital.getSelectedItem();
       
       i.addHospitals(x);
       
      DefaultListModel DLM = new DefaultListModel();
      for( InsurancePolicy ip : ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList())
      {for(int counter=0;counter<ip.getHospitalList().size();counter++)
      {DLM.addElement(ip.getHospitalList().get(counter));
      }
      }
      
      jListHospital.setModel(DLM);
      }
      else{JOptionPane.showMessageDialog(null, "Please create the policy first!");
          
      }
      
        
      
    }//GEN-LAST:event_btnAddHospitalActionPerformed

    private void checkBoxFamilyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxFamilyMousePressed
        // TODO add your handling code here:
          if(checkBoxIndividual.isSelected()==true){
            
                    JOptionPane.showMessageDialog(null, "Only one checkbox can be selected!");
                    checkBoxFamily.setSelected(false);
        }
    }//GEN-LAST:event_checkBoxFamilyMousePressed

    private void checkBoxIndividualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxIndividualMousePressed
        // TODO add your handling code here:
         if(checkBoxFamily.isSelected()==true){
            
                    JOptionPane.showMessageDialog(null, "Only one checkbox can be selected!");
                    checkBoxIndividual.setSelected(false);
        }
    }//GEN-LAST:event_checkBoxIndividualMousePressed

    private void btnAddLaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLaboratoryActionPerformed
         boolean t =ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList().isEmpty();
      if (t==false)
      {  
       String x = (String) jComboLaboratories.getSelectedItem();
    
       i.addLaboratory(x);
       
      DefaultListModel DLL = new DefaultListModel();
      for( InsurancePolicy ip : ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList())
      {for(int counter=0;counter<ip.getLaboratoryList().size();counter++)
      {DLL.addElement(ip.getLaboratoryList().get(counter));
      }
      }
      
      jList2.setModel(DLL);
        }
      else{JOptionPane.showMessageDialog(null, "Please create the policy first!");
          
      }  
    }//GEN-LAST:event_btnAddLaboratoryActionPerformed

    private void btnAddPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPharmacyActionPerformed
        // TODO add your handling code here:
        boolean t =ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList().isEmpty();
      if (t==false)
      {
        String x = (String) jComboPharmacy.getSelectedItem();
    
       i.addPharmacy(x);
       
      DefaultListModel DLP = new DefaultListModel();
      for( InsurancePolicy ip : ecosystem.getInsurancePolicyDirectory().getInsurancePolicyList())
      {for(int counter=0;counter<ip.getPharmacyList().size();counter++)
      {DLP.addElement(ip.getPharmacyList().get(counter));
      }
      }
      
      jList3.setModel(DLP);
      }
      else{JOptionPane.showMessageDialog(null, "Please create the policy first!");
          
      }
    }//GEN-LAST:event_btnAddPharmacyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RButton1;
    private javax.swing.JRadioButton RButton2;
    private javax.swing.JRadioButton RButton3;
    private javax.swing.JRadioButton RButton4;
    private javax.swing.JRadioButton RButton5;
    private javax.swing.JRadioButton RButton6;
    private javax.swing.JRadioButton RButton7;
    private javax.swing.JButton btnAddHospital;
    private javax.swing.JButton btnAddLaboratory;
    private javax.swing.JButton btnAddPharmacy;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JCheckBox checkBoxFamily;
    private javax.swing.JCheckBox checkBoxIndividual;
    private javax.swing.JComboBox<String> jComboHospital;
    private javax.swing.JComboBox<String> jComboLaboratories;
    private javax.swing.JComboBox<String> jComboPharmacy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jListHospital;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField txtDeductible1;
    private javax.swing.JTextField txtDeductible4;
    private javax.swing.JTextField txtEmergencyRoomCare;
    private javax.swing.JTextField txtInpatients;
    private javax.swing.JTextField txtLabServices;
    private javax.swing.JTextField txtMonthly;
    private javax.swing.JTextField txtPolicyMax;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyName1;
    private javax.swing.JTextField txtPrimaryCare;
    private javax.swing.JTextField txtSpecialistCare;
    private javax.swing.JTextField txtSurgery;
    // End of variables declaration//GEN-END:variables
}
