/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.InsurancePolicy.InsurancePolicy;
import Business.Patient.Patient;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anjali
 */
public class ViewPolicyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPolicyWorkAreaJPanel
     */
    InsurancePolicy i;
    JPanel userProcessContainer;
    EcoSystem ecosystem;

    public ViewPolicyWorkAreaJPanel(JPanel userProcessContainer, EcoSystem ecosystem, InsurancePolicy i) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.i = i;
        
            txtPolicyMax.setEnabled(false);
            txtPolicyName.setEnabled(false);
            txtMonthly.setEnabled(false); 
            txtDeductible1.setEnabled(false);
            txtPrimaryCare.setEnabled(false);
            txtAnnualOut.setEnabled(false);
            txtSpecialistCare.setEnabled(false); 
            txtEmergencyRoomCare.setEnabled(false);
            txtSurgery.setEnabled(false);
            txtLabServices.setEnabled(false);
            txtInpatients.setEnabled(false);
            txtZipCode.setEnabled(false);
            txtMin.setEnabled(false);
            txtPolicyType.setEnabled(false);
            
            
            saveUpdateBtn.setEnabled(false);
            viewUpdateBtn.setEnabled(true);
        
        
            txtPolicyMax.setText(i.getPolicyMax());
            txtPolicyName.setText(i.getPolicyName());
            txtMonthly.setText(String.valueOf(i.getMonthlyPremium())); 
            txtDeductible1.setText(String.valueOf(i.getDeductable()));
            txtPrimaryCare.setText(String.valueOf(i.getPrimaryCare()));
            txtAnnualOut.setText(i.getOutOfPocket());
            txtSpecialistCare.setText(String.valueOf(i.getSpecialist())); 
            txtEmergencyRoomCare.setText(String.valueOf(i.getEmergency()));
            txtSurgery.setText(String.valueOf(i.getEmergency()));
            txtLabServices.setText(String.valueOf(i.getEmergency()));
            txtInpatients.setText(String.valueOf(i.getEmergency()));
            txtZipCode.setText(i.getZipCode());
            txtMin.setText(i.getAgeGroup());
            txtPolicyType.setText(i.getPolicyType());
            populateTable();
            populatePharmacy();
            populateLaboratory();
            populateHospitals();
          
    }
    
    
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
            Object row[] = new Object[7];
            row[0] = i.getDental();
            row[1] = i.getLaboratory();
            row[2] = i.getPharmacy();
            row[3] = i.getFitness();
            row[4] = i.getVision();
            row[5] = i.getHearing();
            row[6] = i.getTeleHealth();
            dtm.addRow(row);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMonthly = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPolicyMax = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrimaryCare = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSpecialistCare = new javax.swing.JTextField();
        txtSurgery = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLabServices = new javax.swing.JTextField();
        txtEmergencyRoomCare = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPolicyType = new javax.swing.JTextField();
        saveUpdateBtn = new javax.swing.JButton();
        viewUpdateBtn = new javax.swing.JButton();
        txtMin = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtAnnualOut = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDeductible1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtInpatients = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("<-Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View Insurance Policy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));
        add(txtPolicyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 117, -1));

        jLabel2.setText("Policy Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 74, -1, -1));

        jLabel4.setText("Monthly Premium:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));
        add(txtMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 117, -1));

        jLabel7.setText("Policy Type:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        jLabel6.setText("Age Group :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        add(txtPolicyMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 110, -1));

        jLabel15.setText("Policy Maximum:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Co-Payment After Deductable:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        add(txtPrimaryCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 50, -1));

        jLabel9.setText("Primary Care:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel10.setText("Specialist Care:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));
        add(txtSpecialistCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 50, -1));
        add(txtSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 50, -1));

        jLabel14.setText("Surgery:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 70, -1));

        jLabel13.setText("Laboratory Services:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 150, -1));
        add(txtLabServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 50, -1));
        add(txtEmergencyRoomCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 50, -1));

        jLabel12.setText("Emergency Room Care:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 170, -1));
        add(txtPolicyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 117, -1));

        saveUpdateBtn.setText("Save");
        saveUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUpdateBtnActionPerformed(evt);
            }
        });
        add(saveUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 710, 146, 54));

        viewUpdateBtn.setText("Update");
        viewUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpdateBtnActionPerformed(evt);
            }
        });
        add(viewUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 710, 139, 54));
        add(txtMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 130, 130, -1));

        jLabel39.setText("Annual Out-of Pocket:");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));
        add(txtAnnualOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 117, -1));

        jLabel18.setText("Annual Deductible :");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        add(txtDeductible1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 100, -1));

        jLabel40.setText("Inpatient Admissions:");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 160, -1));
        add(txtInpatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 50, -1));

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("Laboratories included"));
        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 180, 140));

        jList3.setBorder(javax.swing.BorderFactory.createTitledBorder("Hospitals included"));
        jScrollPane3.setViewportView(jList3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 160, 140));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dental", "Laboratory", "Pharmacy", "Fitness", "Vision", "Hearing", "TeleHealth"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 800, 110));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Plan Features:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 110, -1));

        jLabel21.setText("ZipCode:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pharmacy included"));
        jScrollPane4.setViewportView(jList1);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 160, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void saveUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUpdateBtnActionPerformed
        // TODO add your handling code here:
        txtPolicyMax.setEnabled(false);
            txtPolicyName.setEnabled(false);
            txtMonthly.setEnabled(false); 
            txtDeductible1.setEnabled(false);
            txtPrimaryCare.setEnabled(false);
            txtAnnualOut.setEnabled(false);
            txtSpecialistCare.setEnabled(false); 
            txtEmergencyRoomCare.setEnabled(false);
            txtSurgery.setEnabled(false);
            txtLabServices.setEnabled(false);
            txtInpatients.setEnabled(false);
            txtZipCode.setEnabled(false);
            txtMin.setEnabled(false);
            txtPolicyType.setEnabled(false);
            
            saveUpdateBtn.setEnabled(false);
            viewUpdateBtn.setEnabled(true);
    }//GEN-LAST:event_saveUpdateBtnActionPerformed

    private void viewUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpdateBtnActionPerformed
        // TODO add your handling code here:
            txtPolicyMax.setEnabled(true);
            txtPolicyName.setEnabled(true);
            txtMonthly.setEnabled(true); 
            txtDeductible1.setEnabled(true);
            txtPrimaryCare.setEnabled(true);
            txtAnnualOut.setEnabled(true);
            txtSpecialistCare.setEnabled(true); 
            txtEmergencyRoomCare.setEnabled(true);
            txtSurgery.setEnabled(true);
            txtLabServices.setEnabled(true);
            txtInpatients.setEnabled(true);
            txtZipCode.setEnabled(true);
            txtMin.setEnabled(true);
            txtPolicyType.setEnabled(true);
        
        

            i.setAgeGroup(txtMin.getText());
            i.setMonthlyPremium(Double.parseDouble(txtMonthly.getText()));
            i.setOutOfPocket((txtAnnualOut.getText()));         
            i.setPolicyMax(txtPolicyMax.getText());
            i.setPolicyName(txtPolicyName.getText());          
            i.setSpecialist(Integer.parseInt(txtSpecialistCare.getText()));
            i.setPrimaryCare(Integer.parseInt(txtPrimaryCare.getText()));
            i.setPolicyType(txtPolicyType.getText());
            i.setLaboratoryservices(Integer.parseInt(txtLabServices.getText())); 
            i.setDeductable(Integer.parseInt(txtDeductible1.getText()));
            i.setZipCode(txtZipCode.getText());
            i.setEmergency(Integer.parseInt(txtEmergencyRoomCare.getText()));
            i.setSurgery(Integer.parseInt(txtSurgery.getText()));
            i.setInPatients(Integer.parseInt(txtInpatients.getText()));
            
        saveUpdateBtn.setEnabled(false);
        viewUpdateBtn.setEnabled(true);
        
        
            JOptionPane.showMessageDialog(null, " Updated Successfully");
    }//GEN-LAST:event_viewUpdateBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    public void populateHospitals()
    {DefaultListModel DLM = new DefaultListModel();
            
                for (int counter = 0; counter < i.getHospitalList().size(); counter++) {
                    DLM.addElement(i.getHospitalList().get(counter));
                }
                jList3.setModel(DLM);
    }
    
    public void populateLaboratory()
    {DefaultListModel DLM = new DefaultListModel();
            
                for (int counter = 0; counter < i.getLaboratoryList().size(); counter++) {
                    DLM.addElement(i.getLaboratoryList().get(counter));
                }
                jList2.setModel(DLM);
    }
     public void populatePharmacy()
    {DefaultListModel DLM = new DefaultListModel();
            
                for (int counter = 0; counter < i.getPharmacyList().size(); counter++) {
                    DLM.addElement(i.getPharmacyList().get(counter));
                }
                jList1.setModel(DLM);
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveUpdateBtn;
    private javax.swing.JTextField txtAnnualOut;
    private javax.swing.JTextField txtDeductible1;
    private javax.swing.JTextField txtEmergencyRoomCare;
    private javax.swing.JTextField txtInpatients;
    private javax.swing.JTextField txtLabServices;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtMonthly;
    private javax.swing.JTextField txtPolicyMax;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyType;
    private javax.swing.JTextField txtPrimaryCare;
    private javax.swing.JTextField txtSpecialistCare;
    private javax.swing.JTextField txtSurgery;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JButton viewUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
