/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VaccineTestingStaffRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.VaccineCompanyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manasa
 */
public class VaccineTestingStaffWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccineTestingStaffWorkPanel
     */
     private JPanel userProcessContainer;
    private UserAccount account;
    private VaccineCompanyOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;  
        
    public VaccineTestingStaffWorkPanel(JPanel userProcessContainer, UserAccount account, VaccineCompanyOrganization LabOrganization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = LabOrganization;
        this.business = business;
        this.enterprise = enterprise;
        populateLabTestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void populateLabTestTable(){
                       DefaultTableModel model = (DefaultTableModel)testRequestTable.getModel();
        model.setRowCount(0);

        for(LabTestWorkRequest labTest: account.getLabTestWorkQueue().getLabRequestList()){
            Object row[] = new Object[8];
                 row[0] = labTest;
                 row[1] = labTest.getLabTestType();
                 row[2] = labTest.getVaccine();
                 row[3] =labTest.getTester();
                 row[4] = labTest.getReceiver();
                 if(labTest.getResult() == null){
                     row[5] = "";
                 }else{
                 row[5] = labTest.getResult();
                 }
                 if(labTest.getMessage() == null){
                     row[6] = "";
                 }else{
                 row[6] = labTest.getMessage();
                 }
                 

                 
                 
            model.addRow(row);                    
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        testRequestTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAdminister = new javax.swing.JButton();
        btnEmaill = new javax.swing.JButton();
        btnUpdateRes = new javax.swing.JButton();

        testRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TestID", "Type", "VaccineID", "TesterID", "TestingStaff", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(testRequestTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Vaccine Testing Staff Panel");

        btnAdminister.setText("Administer Medicine on Tester");
        btnAdminister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministerActionPerformed(evt);
            }
        });

        btnEmaill.setText("Email Testers");
        btnEmaill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmaillActionPerformed(evt);
            }
        });

        btnUpdateRes.setText("Update Test Results");
        btnUpdateRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEmaill, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminister, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnUpdateRes, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminister, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateRes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmaill, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministerActionPerformed
        // TODO add your handling code here:
        int selectedRow = testRequestTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a Test row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        LabTestWorkRequest labReq= (LabTestWorkRequest)testRequestTable.getValueAt(selectedRow, 0);

        //email testers
        labReq.setResult("Vaccine Administered");
        populateLabTestTable();
    }//GEN-LAST:event_btnAdministerActionPerformed

    private void btnEmaillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmaillActionPerformed
        // TODO add your handling code here:
        int selectedRow = testRequestTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a Test row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        LabTestWorkRequest labReq= (LabTestWorkRequest)testRequestTable.getValueAt(selectedRow, 0);

        //email testers
        labReq.setResult("Email Sent");
        JOptionPane.showMessageDialog(null,"Email sent to Vaccine testers!!!");
        populateLabTestTable();
    }//GEN-LAST:event_btnEmaillActionPerformed

    private void btnUpdateResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateResActionPerformed
        // TODO add your handling code here:
        int selectedRow = testRequestTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a Test row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        LabTestWorkRequest labReq= (LabTestWorkRequest)testRequestTable.getValueAt(selectedRow, 0);

        UpdateResultJPanel updateResJPanel=new UpdateResultJPanel(userProcessContainer,business,enterprise,account,labReq);
        userProcessContainer.add("updateResJPanel",updateResJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUpdateResActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminister;
    private javax.swing.JButton btnEmaill;
    private javax.swing.JButton btnUpdateRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable testRequestTable;
    // End of variables declaration//GEN-END:variables
}
