/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InsuranceAdminOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author sayu
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    
JPanel userProcessContainer;
    EcoSystem ecosystem;
     UserAccount account;
     Enterprise enterprise;
     String patient;
InsuranceAdminOrganization iOrg;
     
    public PatientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,EcoSystem ecosystem,InsuranceAdminOrganization organization) {
         initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.enterprise = enterprise;
        this.iOrg=organization;
        this.account=account;
        
        lblUsername.setText(account.getEmployee().getName());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegisterForInsurance = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnEmergency = new javax.swing.JButton();
        btnBookLab = new javax.swing.JButton();
        btnMedReq = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPatientHistory = new javax.swing.JButton();

        btnRegisterForInsurance.setText("Insurance Details");
        btnRegisterForInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterForInsuranceActionPerformed(evt);
            }
        });

        jButton3.setText("Book Appointment Hospital");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEmergency.setText("Emergency- Ambulance ");
        btnEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmergencyActionPerformed(evt);
            }
        });

        btnBookLab.setText("Book Appointment for Lab");
        btnBookLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookLabActionPerformed(evt);
            }
        });

        btnMedReq.setText("Send Medicine Request");
        btnMedReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedReqActionPerformed(evt);
            }
        });

        lblUsername.setText("<Value>");

        jLabel2.setText("Welcome");

        btnPatientHistory.setText("Patient History");
        btnPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRegisterForInsurance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEmergency, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnPatientHistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMedReq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBookLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsername)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnRegisterForInsurance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBookLab)
                .addGap(24, 24, 24)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(btnEmergency)
                .addGap(17, 17, 17)
                .addComponent(btnMedReq)
                .addGap(18, 18, 18)
                .addComponent(btnPatientHistory)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterForInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterForInsuranceActionPerformed
        // TODO add your handling code here:
        PatientInsuranceWorkAreaJPanel pfi=new PatientInsuranceWorkAreaJPanel(userProcessContainer,account, ecosystem,iOrg);
        userProcessContainer.add("RegisterForInsuranceJPanel",pfi);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRegisterForInsuranceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        for(Patient p:ecosystem.getPatientDirectory().getpatientlist()){
            if(p.getUserName().equals(account.getUsername())){
                System.out.print(p.getInsurance());
               if( p.getInsurance()==null){
                   JOptionPane.showMessageDialog(null,"Please register with an insurance first!", "Warning", JOptionPane.WARNING_MESSAGE);
               }else{
            
         HospitalAppointment seeResultJPanel=new HospitalAppointment(userProcessContainer,account, ecosystem);
        userProcessContainer.add("HospitalAppointment",seeResultJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
               }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBookLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookLabActionPerformed
        // TODO add your handling code here:
        for(Patient p:ecosystem.getPatientDirectory().getpatientlist()){
            if(p.getUserName().equals(account.getUsername())){
                System.out.print(p.getInsurance());
               if( p.getInsurance()==null){
                   JOptionPane.showMessageDialog(null,"Please register with an insurance first", "Warning", JOptionPane.WARNING_MESSAGE);
               }else{
        BookLabJPanel bookLabJPanel=new BookLabJPanel(userProcessContainer,account, enterprise,ecosystem);
        userProcessContainer.add("bookLabJPanel",bookLabJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
               }
            }
        }
    }//GEN-LAST:event_btnBookLabActionPerformed

    private void btnMedReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedReqActionPerformed
        // TODO add your handling code here:
        for(Patient p:ecosystem.getPatientDirectory().getpatientlist()){
            if(p.getUserName().equals(account.getUsername())){
                System.out.print(p.getInsurance());
               if( p.getInsurance()==null){
                   JOptionPane.showMessageDialog(null,"Please register with an insurance first!", "Warning", JOptionPane.WARNING_MESSAGE);
               }else{RequestMedicineJPanel reqMedJPanel=new RequestMedicineJPanel(userProcessContainer,account, enterprise,ecosystem);
        userProcessContainer.add("reqMedJPanel",reqMedJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
               }
            }
        }
    }//GEN-LAST:event_btnMedReqActionPerformed

    private void btnPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientHistoryActionPerformed
        // TODO add your handling code here:
        PatientHistoryJPanel phjp = new PatientHistoryJPanel(userProcessContainer,account,ecosystem);
        userProcessContainer.add("reqMedJPanel",phjp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPatientHistoryActionPerformed

    private void btnEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergencyActionPerformed
        // TODO add your handling code here:
                        EmergencyJPanel emergencyJPanel=new EmergencyJPanel(userProcessContainer,account,ecosystem);
        userProcessContainer.add("emergencyJPanel",emergencyJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEmergencyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookLab;
    private javax.swing.JButton btnEmergency;
    private javax.swing.JButton btnMedReq;
    private javax.swing.JButton btnPatientHistory;
    private javax.swing.JButton btnRegisterForInsurance;
    private javax.swing.JButton jButton3;

    private javax.swing.JButton jButton4;

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
